# Suprimir avisos de MBeans do Hadoop
log4j.logger.org.apache.hadoop.metrics2.util.MBeans=ERROR
# Suprimir avisos de CodecPool (aqueles do zstd que também aparecem)
log4j.logger.org.apache.hadoop.io.compress.CodecPool=ERROR
