# ./trino/catalog/paimon.properties

connector.name=paimon
warehouse=s3://warehouse/paimon
# Endereço do MinIO (o nome do serviço no docker-compose)
fs.s3.endpoint=http://minio:9000
# Credenciais
fs.s3.access-key=admin
fs.s3.secret-key=password
# Necessário para o MinIO local
fs.s3.path-style-access=true
# Como não temos AWS real, usamos isto para satisfazer o driver
fs.s3.region=us-east-1
